# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------
etk_version = '3.0'
project = 'ETK %s Manual' % etk_version
copyright = '2021'
author = 'erin'
doc_author = 'erin, glenl'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo'
]

# .. todo::     - adds a todo item
# .. todolist:: - generates a list of todos
todo_include_todos = True
# todo_emit_warnings = True
# todo_link_only = False

# If true, the ReST sources are included in the HTML build as _sources/name
html_copy_source = False

# Turn off the 'View page source' distraction
html_show_sourcelink = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_suffix = '.rst'
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "default"
try:
    import sphinx_rtd_theme
    html_theme = "sphinx_rtd_theme"
    del sphinx_rtd_theme
except ModuleNotFoundError:
    pass

# A dictionary of options that influence the look and feel of
# the selected theme. These are theme-specific.
html_theme_options = {}
html_theme_path = []
if html_theme == "sphinx_rtd_theme":
    html_theme_options = {
        # included in the title
        "display_version": False,
        "collapse_navigation": True,
        "navigation_depth": -1,
        "logo_only" : False
    }

    extensions.append('sphinx_rtd_theme')

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

rst_prolog = """
.. |ETK_VERSION| replace:: %s
.. |OBJECT| image:: /images/nodes-socket_object.svg
.. |COLLECTION| image:: /images/nodes-socket_collection.svg
.. |GEOMETRY| image:: /images/nodes-socket_geometry.svg
.. |BOOLEAN_FIELD| image:: /images/nodes-socket_boolean_field.svg
.. |BOOLEAN_FIELD_SINGLE| image:: /images/nodes-socket_boolean_field_single.svg
.. |BOOLEAN_SINGLE| image:: /images/nodes-socket_boolean_single.svg
.. |FLOAT_FIELD| image:: /images/nodes-socket_float_field.svg
.. |FLOAT_FIELD_SINGLE| image:: /images/nodes-socket_float_field_single.svg
.. |FLOAT_SINGLE| image:: /images/nodes-socket_float_single.svg
.. |INTEGER_FIELD| image:: /images/nodes-socket_integer_field.svg
.. |INTEGER_FIELD_SINGLE| image:: /images/nodes-socket_integer_field_single.svg
.. |INTEGER_SINGLE| image:: /images/nodes-socket_integer_single.svg
.. |VECTOR_FIELD| image:: /images/nodes-socket_vector_field.svg
.. |VECTOR_FIELD_SINGLE| image:: /images/nodes-socket_vector_field_single.svg
.. |VECTOR_SINGLE| image:: /images/nodes-socket_vector_single.svg
""" % etk_version

rst_epilog = """
.. |ETK_ZIPFILE| replace:: ETK_core-%s.zip
""" % etk_version

# .. |INTEGER| image:: /images/inputs-integer.png
#html_logo = "images/etk-logo.svg"
